repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
        args:
          - --target-version=py38
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        args: []
        additional_dependencies:
          # Type stubs
          - types-PyYAML
          - types-requests
          - types-python-dateutil
          # Typed libraries
          - numpy
          - pystac
          - azure-data-tables
          - pytest
